# Generated by Django 5.0.4 on 2024-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', upload_to='static/profile_pics'),
        ),
    ]
