# Generated by Django 5.0.4 on 2024-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0006_alter_user_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
