# Generated by Django 5.0.4 on 2024-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0007_alter_user_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
